Default: &defaults
  database: beekeeper.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: beekeeper_test.sqlite3
  <<: *defaults

Staging:
  database: beekeeper_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: beekeeper_production.sqlite3
  poolsize: 100
  <<: *defaults
